ALTER TABLE projects ADD COLUMN branch_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE projects ADD COLUMN has_github_pages INTEGER NOT NULL DEFAULT 0;
ALTER TABLE projects ADD COLUMN pages_url TEXT NOT NULL DEFAULT '';
